checksum/urls.py
from django.urls import path
from . import views

app_name = 'checksum'

urlpatterns = [
    path('', views.homeid, name='homeid'),
]

homeid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='checksum/', permanent=True)),
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico')),
    path('admin/', admin.site.urls),
    path('checksum/', include('checksum.urls')),
]

checksum/models.py
from django.db import models

# Create your models here.

checksum/forms.py
from django import forms


class HomeidForm(forms.Form):
    homeid = forms.CharField(
        widget=forms.TextInput(
            attrs={}
        ),
        min_length=7,
        max_length=7,
        required=True
    )

checksum/views.py
from django.shortcuts import render
from .forms import HomeidForm

def homeid(request):
    if request.method == "POST":
        form = HomeidForm()
        request.session['homeid_start'] = str(request.POST['homeid'])
        #lowercase to uppercase
        homeid = change_to_uppercase(str(request.POST['homeid']))

        #replace O to 0
        homeid = homeid.replace("O", "0")

        request.session['homeid_changed'] = homeid

        # check length is 7
        length_status = check_length(homeid)
        if length_status:
            ...
        else:
            request.session['check_num_status'] = "Falsche Länge"
            return render(request, 'checksum/input.html', {'form': form, 'result': request.session})

        # check is alphanumeric
        alphanumeric_status = check_alphanumeric(homeid)
        if alphanumeric_status:
            ...
        else:
            request.session['check_num_status'] = "Ungültige Zeichen"
            return render(request, 'checksum/input.html', {'form': form, 'result': request.session})

        # check 'alter Standard'
        alter_standard_status = check_alter_standard(homeid)
        if alter_standard_status:
            request.session['check_num_status'] = "Home-ID 'Alter Standard'"
            return render(request, 'checksum/input.html', {'form': form, 'result': request.session})

        # check checksum of new Home ID
        homeid = homeid.replace("V", "A")
        homeid = homeid.replace("W", "E")
        homeid = homeid.replace("X", "I")
        homeid = homeid.replace("Y", "O")
        homeid = homeid.replace("Z", "U")
        request.session['check_num_status'] = check_check_number(homeid)

        return render(request, 'checksum/input.html', {'form': form, 'result': request.session})

    form = HomeidForm()
    return render(request, 'checksum/input.html', {'form': form})



def change_to_uppercase(homeid):
    homeid = homeid.upper()
    return homeid


def check_length(homeid):
    length = len(homeid)
    if length == 7:
        length_status = True
    else:
        length_status = False
    return length_status


def check_alphanumeric(homeid):
    alphanumeric_status = homeid.isalnum()
    return alphanumeric_status


def check_alter_standard(homeid):
    if homeid[0].isalpha():
        if homeid[1:7].isnumeric():
            alter_standard_status = True
        else:
            alter_standard_status = False
    else:
        alter_standard_status = False

    return alter_standard_status


def check_check_number(homeid):
    alpha_to_num = {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "A": 10, "B": 11,
                    "C": 12, "D": 13, "E": 14, "F": 15, "G": 16, "H": 17, "I": 18, "J": 19, "K": 20, "L": 21, "M": 22,
                    "N": 23, "O": 24, "P": 25, "Q": 26, "R": 27, "S": 28, "T": 29, "U": 30, "V": 10, "W": 14, "X": 18,
                    "Y": 24, "Z": 30}

    if homeid[0].isnumeric():
        digit0 = int(homeid[0]) * 1
    else:
        digit0 = int(alpha_to_num[homeid[0]]) * 1

    if homeid[1].isnumeric():
        digit1 = int(homeid[1]) * 3
    else:
        digit1 = int(alpha_to_num[homeid[1]]) * 3

    if homeid[2].isnumeric():
        digit2 = int(homeid[2]) * 1
    else:
        digit2 = int(alpha_to_num[homeid[2]]) * 1

    if homeid[3].isnumeric():
        digit3 = int(homeid[3]) * 3
    else:
        digit3 = int(alpha_to_num[homeid[3]]) * 3

    if homeid[4].isnumeric():
        digit4 = int(homeid[4]) * 1
    else:
        digit4 = int(alpha_to_num[homeid[4]]) * 1

    if homeid[5].isnumeric():
        digit5 = int(homeid[5]) * 3
    else:
        digit5 = int(alpha_to_num[homeid[5]]) * 3

    digit_sum = digit0 + digit1 + digit2 + digit3 + digit4 + digit5

    while digit_sum > 30:
        digit_sum = digit_sum - 31

    check_num = ''
    for x in alpha_to_num:
        if alpha_to_num[x] == digit_sum:
            check_num = x

    if homeid[6] == check_num:
        check_num_status = "Gültige Home-ID"
    else:
        check_num_status = "!!! keine gültige Home-ID !!!"

    return check_num_status

checksum/templates/base.html
<!doctype html>
<html lang="de">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>

<body>
    {% include "header.html" %}

    {% block nav %}{% endblock %}

    {% block content %}{% endblock %}

    {% include "footer.html" %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<script src="{% static 'base.js' %}"></script>


</body>
</html>

checksum/templates/checksum/datenschutz.html
{% extends "base.html" %}

{% block title %}
    Datenschutz
{% endblock %}

{% block content %}
<content>
    <div class="container container_extend">
        <p></p>
        <div class="row">
            <div class="col-sm">
                <button type="button" class="btn btn-secondary" onclick="history.go(-1)">zurück</button>
            </div>
        </div>
    </div>
</content>


{% endblock %}

checksum/templates/checksum/impressum.html
{% extends "base.html" %}

{% block title %}
    Impressum
{% endblock %}

{% block content %}
<content>
    <div class="container container_extend">
        <p></p>
        <div class="row">
            <div class="col-sm">
                <button type="button" class="btn btn-secondary" onclick="history.go(-1)">zurück</button>
            </div>
        </div>
    </div>
</content>


{% endblock %}

checksum/templates/checksum/index.html
{% extends "base.html" %}

{% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'base.css' %}">
{% endblock %}

{% block nav %}

{% endblock %}

{% block content %}
<content>
    <div class="container">
         <div class="form-group row">
               <div class="col-sm-4">
                   <h5>Home ID checken:</h5>
               </div>
           </div>
    </div>
</content>
{% endblock %}

checksum/templates/checksum/input.html
{% extends "base.html" %}

{% load static %}

{% block nav %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'order:index' %}" class="navbar-brand">Startseite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item">
            </li>
            <li class="nav-item">
            </li>
        </ul>
    </div>
</nav>
{% endif %}

{% endblock %}

{% block content %}

<div class="container container_extend">
    <form action="{% url 'checksum:homeid' %}" method="post">
            {% csrf_token %}

    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col form-group text-center">
            <label for="{{ form.homeid.id_for_label }}">Home-ID:</label><br>
                        {{ form.homeid }}
                        {{ form.homeid.errors }}
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <button type="submit" class="btn btn-secondary">Home ID checken</button>
        </div>
    </div>
        <br>
        <br>
    <div class="row">
        <div class="col form-group text-center">
            Eingegebene HomeID: {{ result.homeid_start }}
        </div>
    </div>
    <div class="row">
        <div class="col form-group text-center">
            Angepasste HomeID: {{ result.homeid_changed }}
        </div>
    </div>


    <div class="row">
        <div class="col form-group text-center">
            Status: {{ result.check_num_status }}
        </div>
    </div>
    </form>
</div>

{% endblock %}

checksum/templates/checksum/result.html
{% extends "base.html" %}

{% load static %}

{% block nav %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'order:index' %}" class="navbar-brand">Startseite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav">
            <li class="nav-item">
            </li>
            <li class="nav-item">
            </li>
        </ul>
    </div>
</nav>
{% endif %}

{% endblock %}

{% block content %}

<div class="container container_extend">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col form-group text-center">
            <div class="row">
                <div class="col">
                    Eingegebene Home-ID:
                </div>
                <div class="col">
                    {{ result.id }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    Länge:
                </div>
                <div class="col">
                    {{ result.length }} {{ result.status }}
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col text-center">
        </div>
    </div>
</div>

{% endblock %}

checksum/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

checksum/templates/header.html
    {% load static %}
<div class="container">
    <div class="row">
        <div class="col-1">&nbsp;</div>
        <div class="col">

        </div>
        <div class="col-1">&nbsp;</div>
    </div>
</div>